### ISSUE TITLE
file is corrupt

### ISSUE THREAD

**Issue by DeceptedPar** [MAZ12211/NostalgicFunkin#4]
when downloading this through either the git clone function through git or through github, the file comes up corrupt meaning I can't extract any files

**Comment by Itzbeepi77** [comment]
Download it again it should be working sometimes the issues is your internet I alr countered this issues

**Comment by DeceptedPar** [comment]
I've downloaded it 3 times in a row with failure
first two times were through github, it told me it was corrupt, third time was through git, I got a fatal error

**Comment by DeceptedPar** [comment]
issue has been fixed
